### ISSUE TITLE
Strange white lines occur while draging a node

### ISSUE THREAD

**Issue by hooyuser** [paceholder/nodeeditor#294]
I tried two examples `calculator` and `example2` and found there were some strangle white lines when I dragged a node. Here is my screenshot.

![node](https://user-images.githubusercontent.com/10691820/146537895-abdabf13-ec5f-42dd-9ebc-7f7cc12237d6.png)

These white lines will disappear altogether if I zoom in or zoom out.

**Comment by paceholder** [comment]
I've seen that on Windows, it might have been a debug build. Seems like a Qt bug. Do you mange to reproduce it with a more recent Qt version and with the Release build?

**Comment by facontidavide** [comment]
I have the same problem on Ubuntu, Qt 6.2.3

**Comment by facontidavide** [comment]
I think I fixed the issue with some googling: https://stackoverflow.com/questions/47265389/qgraphicsview-rubberbanddrag-leaves-artifacts

add `setViewportUpdateMode(QGraphicsView::BoundingRectViewportUpdate);` to `GraphicsView` constructor.

**Comment by paceholder** [comment]
I've pushed the fix with the changes proposed in @facontidavide 's link. I don't think I can do more than that because I cannot reproduce it.

My setup: Linux, Qt 6.2.4, GCC 11.2.0

**Comment by aldric-diamoco** [comment]
> I've pushed the fix with the changes proposed in @facontidavide 's link. I don't think I can do more than that because I cannot reproduce it.
> 
> My setup: Linux, Qt 6.2.4, GCC 11.2.0

Hi, thank you, I did the patch myself, as I said it partially solved the problem. Looks like old days backbuffer problems. I'll take one day today to see if I can solve it without breaking the code too much.(Sorry for my english)

**Comment by aldric-diamoco** [comment]
Solved. While I don't really know why. Applied your patch AND update my qt to 6.3 makes your nodeeditor runs smoothly without artifact. I have one or two questions to ask about using it, may I contact you via e-mail?

**Comment by paceholder** [comment]
@aldric-diamoco,

sorry, just noticed your last question. Sure, you can contact me via e-mail.
Closing this issue for now.
